openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /users:
    get:
      tags:
        - chatterbook-controller
      operationId: getAllRecords
      parameters:
        - name: user
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{name}:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserChatter
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /chat/{name}:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserChatterPost
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatterPost'
components:
  schemas:
    ChatterPost:
      type: object
      properties:
        text:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        chatterPost:
          type: array
          items:
            $ref: '#/components/schemas/ChatterPost'
        chatterPosts:
          type: array
          writeOnly: true
          items:
            $ref: '#/components/schemas/ChatterPost'
